.PHONY: clean All

All:
	@echo "----------Building project:[ God_Game - Debug ]----------"
	@$(MAKE) -f  "God_Game.mk"
clean:
	@echo "----------Cleaning project:[ God_Game - Debug ]----------"
	@$(MAKE) -f  "God_Game.mk" clean
